[package]
authors = ["Tristan Britt <hello@tbritt.xyz>", "0xAlcibiades <alcibiades.eth@protonmail.com>"]
categories = ["cryptography", "mathematics"]
description = "Implementation of the BLS signature scheme using the alt-bn128 curve."
homepage = "https://github.com/warlock-labs/alt-bn128-bls"
keywords = ["alt-bn128", "bls", "cryptography", "elliptic-curve", "pairing"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/warlock-labs/alt-bn128-bls.git"
name = "alt-bn128-bls"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex-literal = "0.4.1"
num-traits = "0.2.19"
subtle = "2.6.1"
crypto-bigint = { git = "https://github.com/RustCrypto/crypto-bigint.git", features = ["rand_core"]}
rand = "0.9.0-alpha.1"
rand_chacha = "0.9.0-alpha.1"

[lib]
proc-macro = true
[dev-dependencies]
