

# This file was *autogenerated* from the file src/fields/ref.sage
from sage.all_cmdline import *   # import sage library

_sage_const_21888242871839275222246405745257275088696311157297823662689037894645226208583 = Integer(21888242871839275222246405745257275088696311157297823662689037894645226208583); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_32 = Integer(32); _sage_const_64 = Integer(64); _sage_const_128 = Integer(128); _sage_const_256 = Integer(256); _sage_const_512 = Integer(512); _sage_const_1024 = Integer(1024); _sage_const_2048 = Integer(2048); _sage_const_4096 = Integer(4096); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_0x0000000000000001000000000000000200000000000000030000000000000004 = Integer(0x0000000000000001000000000000000200000000000000030000000000000004); _sage_const_0x0000000000000001000000000000000100000000000000010000000000000001 = Integer(0x0000000000000001000000000000000100000000000000010000000000000001); _sage_const_0x0000000000000004000000000000000300000000000000020000000000000001 = Integer(0x0000000000000004000000000000000300000000000000020000000000000001); _sage_const_0x0000000000000000000000000000000000000000000000000000000000000009 = Integer(0x0000000000000000000000000000000000000000000000000000000000000009); _sage_const_0x0000000000000000000000000000000000000000000000000000000000000001 = Integer(0x0000000000000000000000000000000000000000000000000000000000000001); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3)
p =_sage_const_21888242871839275222246405745257275088696311157297823662689037894645226208583 
Fp = GF(p)

Fp2 = GF(p**_sage_const_2 , modulus=x**_sage_const_2 +_sage_const_1 , names=('u',)); (u,) = Fp2._first_ngens(1)
def determine_uint_size(n):
    bit_length = n.nbits()

    if bit_length <= _sage_const_8 :
        return "U8"
    elif bit_length <= _sage_const_16 :
        return "U16"
    elif bit_length <= _sage_const_32 :
        return "U32"
    elif bit_length <= _sage_const_64 :
        return "U64"
    elif bit_length <= _sage_const_128 :
        return "U128"
    elif bit_length <= _sage_const_256 :
        return "U256"
    elif bit_length <= _sage_const_512 :
        return "U512"
    elif bit_length <= _sage_const_1024 :
        return "U1024"
    elif bit_length <= _sage_const_2048 :
        return "U2048"
    elif bit_length <= _sage_const_4096 :
        return "U4096"
    else:
        return f"Needs more than 2048 bits (actual: {bit_length} bits)"

def u256_to_u64_list_hex(u256_value):
    if u256_value < _sage_const_0  or u256_value >= _sage_const_2 **_sage_const_256 :
        raise ValueError("Input must be a 256-bit non-negative integer")

    # Convert to 256-bit binary string, pad with zeros if necessary
    binary = format(u256_value, '0256b')
    
    # Split into 4 64-bit chunks (little-endian order)
    chunks = [binary[i:i+_sage_const_64 ] for i in range(_sage_const_0 , _sage_const_256 , _sage_const_64 )]
    chunks.reverse()  # Reverse for little-endian

    # Convert each chunk to an integer and then to hex
    hex_list = [hex(int(chunk, _sage_const_2 )) for chunk in chunks]
    
    return hex_list

def u64_list_to_u256(u64_list):
    if len(u64_list) != _sage_const_4 :
        raise ValueError("Input list must contain exactly 4 u64 integers")
    
    # Convert each u64 to 64-bit binary string, ensuring 64 bits
    binary_strings = [format(x & ((_sage_const_1  << _sage_const_64 ) - _sage_const_1 ), '064b') for x in u64_list]

    # Reverse the list for little-endian
    binary_strings.reverse()

    # Concatenate all binary strings
    full_binary = ''.join(binary_strings)

    # Convert binary string to integer
    return int(full_binary, _sage_const_2 )


# u64_list = [
#     0x3C208C16D87CFD47,
#     0x97816A916871CA8D,
#     0xB85045B68181585D,
#     0x30644E72E131A029
# ]

# u256_value = u64_list_to_u256(u64_list)

# print(f"u256 value: {u256_value}")
# print(f"In hexadecimal: {hex(u256_value)}")

# from_words = lambda arr: hex(u64_list_to_u256(arr))
# print(from_words([1,1,1,1]))
# a = Fp2(from_words([1,1,1,1]), from_words([1,1,1,1]))
# b = Fp2(from_words([1,1,1,1]), from_words([1,1,1,1]))
# print(from_words([4,3,2,1]))

a = Fp2(_sage_const_0x0000000000000001000000000000000200000000000000030000000000000004  + u*_sage_const_0x0000000000000001000000000000000100000000000000010000000000000001 )
b = Fp2(_sage_const_0x0000000000000001000000000000000100000000000000010000000000000001  + u*_sage_const_0x0000000000000004000000000000000300000000000000020000000000000001 )
c = a/b
c0, c1 = [u256_to_u64_list_hex(int(i)) for i in list(c)]
#print(c0)
#print(c1)
# print(u64_list_to_u256([0x2221d7e243f5a6b7, 0xf2dbb3e54415ac43, 0xc1c16c86d80ba3fe, 0x1ed70a64be2c4cf4]))
# print(list(c)[0])

nonres = Fp2(_sage_const_0x0000000000000000000000000000000000000000000000000000000000000009 +u
*_sage_const_0x0000000000000000000000000000000000000000000000000000000000000001 )
e = (_sage_const_2 *p**_sage_const_5 -_sage_const_2 )/_sage_const_3 
d = nonres**(e)
print(d)
for i in list(d):
    h = u256_to_u64_list_hex(int(i))
    print("Fp::new(U256::from_words([\n")
    for j in h:
        print(f"\t{j},\n")
    print("]))")


