[tool.poetry]
name = "alt-bn128-bls"
version = "0.1.0"
description = ""
authors = ["Tristan <hello@tbritt.xyz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"